### ISSUE TITLE
standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by Juandavi1** [grafana/xk6#27]
Hi guys, 

we have an extension that works well locally but when we are going to test it in a container it fails.

We are compiling the binary as follows:
`xk6 build v0.33.0 --with dev.azure.com/SiigoDevOps/Siigo/_git/Siigo.K6.Extensions.git=$(pwd)`
and 
`CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 xk6 build v0.33.0 --with dev.azure.com/SiigoDevOps/Siigo/_git/Siigo.K6.Extensions.git=$(pwd)`

but the container does not work generating the following error

`standard_init_linux.go:219: exec user process caused: exec format error`

Do you know what it could be? we have tried everything but we have not succeeded :(

thanks

**Comment by MStoykov** [comment]
Are you sure the container you are running isn't actually linux instead of macos? even if it's running on top of mac. In that case you would not use `GOOS=darwin` but `GOOS=linux` ;)

**Comment by Juandavi1** [comment]
Hi, yes now it works 

Thanks
