### ISSUE TITLE
Unable to set local path to build from Fork

### ISSUE THREAD

**Issue by mjkapkan** [grafana/xk6#28]
Hi,

I need to build from source of a specific branch. So I pulled to branch and tried to build it, but it looks like the path is not accepted:
```
$ XK6_K6_REPO="$PWD" xk6 build

2021/08/24 11:52:11 [INFO] Temporary folder: /tmp/buildenv_2021-08-24-1152.237197142

2021/08/24 11:52:11 [INFO] Writing main module: /tmp/buildenv_2021-08-24-1152.237197142/main.go

2021/08/24 11:52:11 [INFO] Initializing Go module

2021/08/24 11:52:11 [INFO] exec (timeout=10s): /home/jaunius/.gvm/gos/go1.16.6/bin/go mod init k6 

go: creating new go.mod: module k6

go: to add module requirements and sums:

	go mod tidy

2021/08/24 11:52:11 [INFO] Pinning versions

2021/08/24 11:52:11 [INFO] exec (timeout=0s): /home/jaunius/.gvm/gos/go1.16.6/bin/go mod edit -require go.k6.io/k6@latest 

2021/08/24 11:52:11 [INFO] exec (timeout=10s): /home/jaunius/.gvm/gos/go1.16.6/bin/go mod edit -replace 
go.k6.io/k6=/home/jaunius/dev/builds/xk6/k6 

go: errors parsing go.mod:

/tmp/buildenv_2021-08-24-1152.237197142/go.mod:5: require go.k6.io/k6: version "latest" invalid: must be of the form v1.2.3

2021/08/24 11:52:11 [INFO] Cleaning up temporary folder: /tmp/buildenv_2021-08-24-1152.237197142

2021/08/24 11:52:11 [FATAL] exit status 1
```

**Comment by MStoykov** [comment]
can you please try to run `go install go.k6.io/xk6/cmd/xk6@latest` and try again?

**Comment by mjkapkan** [comment]
Thanks! That worked. Looks like I might have missed one step.

**Comment by MStoykov** [comment]
We had a bug last week you like didn't upgrade since then :).

> Is there any way to build directly from repository fork instead of pulling it first locally?

Are you talking about a k6 fork or an extension fork ... I think in both case you can just give the fork "url" instead.

**Comment by mjkapkan** [comment]
Apologies for the confusion, what I meant is a specific branch. Like this: 
`--branch feature/SourceMaps https://github.com/grafana/k6.git`

**Comment by MStoykov** [comment]
You can use `K6_VERSION=whatever xk6 build ...` but it [doesn't work](https://github.com/golang/go/issues/38861) with branches with `/` in them, but it works with commit has so `K6_VERSION=1065bcf xk6 build ...` works .

**Comment by imiric** [comment]
Closing this as it appears to be fixed, but let us know if not @mjkapkan.
