### ISSUE TITLE
Consumer waits 10 minutes when no message are coming

### ISSUE THREAD

**Issue by Bewi42** [grafana/xk6#31]
Hello,
I run a script where I produce a message to a topic A then waits for another message on a topic B.
Sometimes, message is not posted on topic B, and I would like the consumer to wait a few seconds, no more. Currently, it waits around 10 minutes.
I don't really understand why as I see that the MaxWait is configured to 200ms in the go consumer class.

**Comment by MStoykov** [comment]
I would expect this is a bug meant for an extension, so please report it to it's issues :)

**Comment by Bewi42** [comment]
Oh yes sorry I was on the wrong place !
