### ISSUE TITLE
Failure to install xk6

### ISSUE THREAD

**Issue by unlikelyzero** [grafana/xk6#36]
I'm just including this on the xk6 issue tracker for discoverability.

I installed go using the .pkg file and with brew. In both cases, I ended up with the following error:
$ go version
go version go1.17.6 darwin/amd64
$ go install go.k6.io/xk6/cmd/xk6@latest
$ xk6
zsh: command not found: xk6

The solution was not totally clear in this related discussion: https://community.k6.io/t/unable-to-locate-xk6-after-installing-it/1866

Here is a gist which helps handle every case https://gist.github.com/vsouza/77e6b20520d07652ed7d

**Comment by imiric** [comment]
Hi, thanks for reporting this!

We'll consider linking to that gist from the README.

**Comment by javaducky** [comment]
Just wanted to add a note with regard to the described [gist](https://gist.github.com/vsouza/77e6b20520d07652ed7d): 

If you are using Homebrew to install Go on Apple silicon (i.e. M1 processors), keep in mind that [Homebrew installation](https://docs.brew.sh/Installation) has changed the preferred prefix from `/usr/local` to `/opt/homebrew`. 

For this reason, you cannot simply copy/paste from that gist for your specific shell.
