### ISSUE TITLE
xk6 binary works fine locally, but fails in CI

### ISSUE THREAD

**Issue by Light-Leo** [grafana/xk6#84]
I was using k6 v0.32.0, and after updating to a higher version (v0.45.1), the CI runs started failing during the build stage:

```bash
xk6 build v0.45.1 \
  --with github.com/tmieulet/xk6-cognito \
  --with github.com/MyPackage/xk6-email="${{ github.workspace }}/k6-tests/extensions/xk6-email"
```

Despite fixing the build issue, running k6 tests in the CI pipeline now fails, even though the same tests and build work fine locally. The error is as follows:

```plaintext
Copy code
          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

time="24-01-17T09:28:56Z" level=error msg="TypeError: could not convert function call parameter 0: could not convert *** to context.Context\n\tat reflect.methodValueCall (native)\n\tat webpack://k6/./src/auth/AuthProvider.ts:24:41(75)\n\tat webpack://k6/./src/account/AccountManager.ts:20:24(31)\n\tat webpack://k6/./src/index.ts:12:23(286)\n\tat file:///home/k6/main.js:764:12(3)\n" hint="script exception"
```

No code changes were made. The CI runs on Ubuntu 22.04 LTS (amd64), while locally it works on Darwin Kernel, macOS (x86_64).

Also, it fails if using a locally built docker image with the same error:

``` bash
docker run --rm -v $PWD/build-output/:/home/k6 lightleo/xk6-ext:v0.0.1 run /home/k6/main.js
```

**Comment by pablochacin** [comment]
Hi @Light-Leo Thanks for reporting this issue. 

First at all, going from k6 `v0.32.0` to `v.0.45.1.` is quite a big jump, there are many things that may have changed in between regarding extensions and the underlying goja runtime. 

In particular you may be hitting [this issue](https://github.com/grafana/k6/issues/1802).

I suggest you take a look at the updated documentation on [JavaScript Entensions ](https://grafana.com/docs/k6/latest/extensions/create/javascript-extensions/)and the [Go-to-JS bridge](https://grafana.com/docs/k6/latest/extensions/explanations/go-js-bridge/). 

Hope this helps.

**Comment by pablochacin** [comment]
Close as this is not a `xk6` bug.
